### PR TITLE
Update questionnaire-en.json

### PR DESCRIPTION
**Pull request by hakssung**
update titles. because there are no goals at spec v2.0 anymore.

### CODE REVIEW

**Comment by goneall** [comment]
@shanecoughlan If you could do a quick review and approve the changes to the section headings, I'll go ahead and merge.

**Comment by shanecoughlan** [comment]
Approved!

**Comment by goneall** [comment]
@hakssung Thanks for the contribution!  Merged the PR.  I ran into an issue with fonts in generating the PDF (see issue #34 ).  Hope to have some time to look into it next week.

**Comment by shanecoughlan** [comment]
FYI, Korean is not showing up on the web app yet.

**Comment by shanecoughlan** [comment]
Ah, just saw your note about going live.

==

I can upload the translated questionnaire to the web app, but we need to have the Ui translations for Korean before they will show up.  See the README at https://github.com/OpenChain-Project/Online-Self-Certification-Web-App for a description of the files that need to be localized.

==

Over to @hakssung

**Pull request merged**
